import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Autogenerated sidebar - no manual editing needed!
  // Sidebar structure comes from folder structure + frontmatter
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from the docs folder
    },
  ],
};

export default sidebars;
